gongshare/account/urls.py
# -*- encoding=utf-8 -*-
from django.conf.urls import patterns,url


urlpatterns = patterns("account.views",
            url(r'^login/(?P<login_type>\w+)/$', 'third_login', name='login'),
            url(r'^login/weibo/done/$', 'weibo_auth'),
            url(r'^github_login/$', 'github_login'),
            url(r'^github_callback', 'github_callback'),
            url(r'^weibo_login/$', 'weibo_login', name='weibo_login'),
            url(r'^logout/$', 'logout', name='logout'),
            url(r'^islogin/$', 'islogin'),
            url(r'^weibo_post/$', 'weibo_post'),
            url(r'^short_url/$', 'short_url'),
            url(r'^login/$', 'login', name="login"),
            url(r'^signup/$', 'signup', name="signup"),
            url(r'^captcha/$', 'form_valid'),
            url(r'^reg_confirm/(?P<uuid>\S{36})/$', 'user_active', name='user_active'),
            


       ) 

gongshare/gongshare/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
     url(r'^my_admin/', include(admin.site.urls)),
     url(r'^$', include('subject.urls', namespace='index')),
     url(r'^search/$', 'subject.views.search'),
     url(r'^subject/', include('subject.urls', namespace='subject')),
     url(r'^account/', include('account.urls', namespace='account')),
     url(r'^people/', include('people.urls', namespace='people')),

     url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root':settings.STATIC_PATH}),
     url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT}),
     url(r'^tinymce/', include('tinymce.urls')),

     url(r'^report/', include('report.urls')),
     url(r'^about/$', 'website.views.about', name='about'),
     url(r'^feedback/$', 'website.views.feedback'),
     url(r'^changelog/$', 'website.views.changelog', name='changelog'),
)

urlpatterns += patterns('',
        url(r'^captcha/', include('captcha.urls'),)
)

gongshare/people/urls.py
# -*-encoding=UTF-8 -*-
from django.conf.urls import patterns,url

urlpatterns = patterns('people.views',
    url(r'^(\d{1,9})/$', 'index', name='index'),
    url(r'^(\d{1,9})/favour$','favour'),
    url(r'^(\d{1,9})/edit_intro/$','edit_intro'),
)

gongshare/subject/urls.py
# -*-encoding=UTF-8 -*-
from django.conf.urls import patterns,url

urlpatterns = patterns('subject.views',
    url(r'^hot/$','subjects', name='hot'),
    url(r'^$','recent', name='index'),
    url(r'^recent/$', 'recent', name='recent'),
    url(r'^(\d+)/$','subject_detail',name='detail'),
    url(r'^tag_search2/$','tag_search2'),
    url(r'^add_subject/$','add_subject'),
    url(r'^(\d{1,9})/favour/$','subject_favour'),
    url(r'^(\d{1,9})/comment/add/$','add_comment'),
    url(r'^comment/(\d{1,9})/like/$','comment_like'),
    url(r'^ajax/$','subject_search_by_url'),
    url(r'^delete/(\d{1,9})/$','delete_subject'),
    url(r'^comment/(\d{1,9})/delete/$','delete_comment'),
    url(r'^(\d{1,9})/edit/$', 'edit_subject', name='edit'),
)

gongshare/utils/urls.py
# -*- encoding=utf-8 -*-
from django.shortcuts import redirect

def login_redirect(request):
    """
    跳转至登录或注册成功前的链接
    - next param
    """ 
    next = request.REQUEST.get("next", "/")
    return redirect(next)


gongshare/people/models.py
from django.db import models

# Create your models here.

gongshare/people/views.py
# -*- encoding=UTF-8  -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.conf import settings
from account.models import MyUser
from paginator.Paginator import paginate
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.csrf import csrf_exempt
from account.functions import ajax_login_required
import os,json

def index(request,user_id): 
    '''user_id的首页，默认显示该username发表的主题'''
    try:
        user = MyUser.objects.get(pk=user_id)
        subject_list = user.post_subjects.all().order_by('-pub_date')
        filename = os.path.split(user.avatar)[1]
        return paginate('subject_list',subject_list,request,'people.html',user=user,avatar=filename)
    except MyUser.DoesNotExist:
        raise Http404        

def favour(request,user_id): 
    '''user_id 赞过的主题'''
    try:
        user = MyUser.objects.get(pk=user_id)
        subject_list = user.vote_subjects.all().reverse()#.order_by('-id')
        filename = os.path.split(user.avatar)[1]
        return paginate('subject_list',subject_list,request,'people.html',user=user,avatar=filename,favoured=True)
    except MyUser.DoesNotExist:
        raise Http404

@csrf_exempt
@ajax_login_required
def edit_intro(request,user_id):
    content = request.POST.get('content')
    user = request.session['user_']
    user.signature = content
    user.save()
    data = {'msg':'success'}
    return HttpResponse(json.dumps(data,separators=(',',':')),
                        mimetype='application/json;charset=UTF-8') 

gongshare/templates/about.html
{% extends "base.html" %}
{% block title %}关于公舍{% endblock %}
{% block content %}  
    {% autoescape off %}
    {{about.content}}
    {% endautoescape %}
{% endblock %}

{% block people %}
    {% autoescape off %}
    {{about.author_info}}
    {% endautoescape %}
{%endblock %}

gongshare/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
{% load url from future %}
<html lang="en" >
 <head>
       <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
       <title>{% block title %}{% endblock %}</title>
       <meta name="description" content="Python编程,Django框架,数据库,动态编程语言,MySQL">
       <meta name="keywords" content="Python编程 Java编程 Django框架 gongshare技术分享">
	   <link href="/site_media/autocomplete.css" rel="stylesheet" type="text/css">
	   <link href="/site_media/content.css" rel="stylesheet" type="text/css">
	   <link href="/site_media/gavacafe.css" rel="stylesheet" type="text/css">
	   <link href="/site_media/tipsy.css" rel="stylesheet" type="text/css">
	   <link href="/site_media/zebra_dialog.css" rel="stylesheet" type="text/css">
</head>
<body>
<div id="wrapper">
	<div  id="nav-wrapper">
		<div id="top-inner">
				<div class="row relative">
					<div class="logo">
                        <a class="w1" href="{% url 'index:index' %}">gongshare</a>
					</div>
					<ul class="nav_list nav_list_reorg">
						<li class="nav-user-account">
						{% if user_ %}
                        <a target="_blank" href="javascript:;" class="bn-more nav_item has_nav_menu" rel="off">
                            <span>{{user_.username}}</span></a>
						 <div class="more-items">
						 <ul class="login-dropdown" style="display:block">
                             <li><a href="{% url 'people:index' user_.id %}">我的公舍</a></li>
                             <li><a href="{% url 'account:logout'%}">退出</a></li>
                         </ul>
						 </div>
						{% else %}
                        <a href="{% url 'account:login'%}" class="bn-more nav_item " rel="off">
                            <span>登录</span>
                        </a>
                        <a href="{% url 'account:signup'%}" class="bn-more nav_item " rel="off">
                            <span>注册</span>
                        </a>
                        <!--
						<div class="more-items">
						 <ul class="share-link login-dropdown" style="display:block">
							<li><a class="s-sina" href="/account/login/weibo">微博登录</a></li>
						 </ul> 
						</div>
                        -->
						{% endif %}
						</li>
					</ul>
					<div id="context-navigator">
						<div class="search full_search instant_results">
							<div class="search_contents navigator">
								<form class="search_form" action="#" onsubmit="return false;" method="get" name="search_form">
									<div class="search_input">
										<div class="input_wrapper">
											<span class="input_icon" id="__w2_mh4TQOu_input_icon"></span>
                                            <input class="question_box light"  name="search_input" type="text" 
                                                value="{%if query_key %}{{query_key}}{%endif %}" maxlength="250"  
                                                placeholder="搜索标签、资源" >
                                                <button type="submit" class="search-button">
                                                    <i class="icon-search"></i>
                                                <span class="hide-text">搜索</span></button>
										</div>
									</div>
								</form>
								<div id="result_shell"></div>
							</div>
						</div>
						<a href="{% url 'index:index' %}" class="index"><span>首页</span></a>
					</div>
				</div>
		</div>
	</div>


	<div class="main clearfix">
		<div class="left fl">
		 {% block content %}{% endblock %}
		</div>
        <div class="aside">
            {% block aside %}{% endblock %} 
        </div>
	</div>
	<div id="footer">
    <ul>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'changelog' %}">Changelog</a></li> 
<!--
        <li>
        <a class="advice" href="/feedback">吐槽</a>
        </li>
-->
    </ul>
        <span style="float:right">本站推荐使用<a href="http://www.google.cn/intl/zh-CN/chrome/browser/">Chrome</a>或<a href="http://firefox.com.cn/download/">Firefox</a>浏览器</span>
	</div>
</div>

       <script type="text/javascript" src="/site_media/jquery-1.8.2.min.js"></script>
       <script type="text/javascript" src="/site_media/jquery.tipsy.js"></script>
       <script type="text/javascript" src="/site_media/jquery.autocomplete.js"></script>
       <script type="text/javascript" src="/site_media/zebra_dialog.js"></script>
       <script type="text/javascript" src="/site_media/gavacafe.js"></script>
             <script>
             (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
               (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                   })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
                     ga('create', 'UA-42613705-1', 'gongshare.com');
                       ga('send', 'pageview');
       </script>

</body>
</html>

gongshare/templates/changelog.html
{% extends "base.html" %}
{% load myapp_markup %}
{% block title %} changelog {% endblock %}
{% block content %}
{{content|my_markdown}}
{% endblock %}


gongshare/templates/comment.html
<div class="zm-item-comment" data-id="{{comment.id}}">
    <div class="zm-comment-content-wrap">
        <div class="zm-comment-hd">
            <a href="/people/{{comment.user.id}}" class="zg-link">{{comment.user.username}}</a>
            {% if comment.comment %}
            <span class="desc">回复 </span>
            <a  href="/people/{{comment.comment.uesr.id}}" class="zg-link" >{{comment.comment.user.username}}</a>
            {% endif %}
        </div>

        <div class="zm-comment-content">
            {% if comment.comment %}
            <blockquote>
                <p>{{comment.comment.content}}</p>
            </blockquote>
            {% endif %}
            <p>{{comment.content}}</p>
        </div>
        <div class="zm-comment-ft">

            <a href="javascript:;" name="delete" class="delete zm-comment-op-link">删除</a>

            <span class="date">{{comment.pub_date|date:"Y-m-d"}}</span>
        </div>
    </div>
</div>


gongshare/templates/feedback.html
{% extends "base.html" %}
{% block title %}反馈与建议{% endblock %}
{% block content %}  
<div id="writeTips" class="welcome">
    <i class="i_bubble"></i>
    <p>您好，欢迎给本站提使用感受和建议！首先说好啦，任何版本的IE以及IE内核游览器下的Bug都不算是Bug</p>
</div>
		
	

<div class="feedback_form">
    <ul>
        <li>
        <span class="label">内容：</span>
        <textarea style="width:498px;height:140px"></textarea>
        </li>
        <li>
        <span class="label">您的邮箱：</span>
        <input type="text" id="contact_text" required="true" style="width:200px;height:23px"/>
        <div class="prompt">（方便我们及时告知您处理结果）</div>
        </li>
        <li>
        <span class="label">上传图片：</span>
        <input type="file"/>
        </li>
        <li>
        <input type="submit" value="提 交" class="btn_gray" style="margin-left:100px"/>
        </li>
    </ul>
</div>



{% endblock %}





u@)!!)%@&

gongshare/templates/login.html
{% extends "base.html" %}
{% block title %}登录{% endblock %}
{% block content %}  
<div id="content">
    <div class="title">登录公舍</div>
    <div class="login_form">
    <span class='error'>{{error}}</span>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
            <span class='error'>{{ error|escape }}</span>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <span class='error'>{{ error|escape }}</span>
        {% endfor %}
    {% endif %}
            
		<div class="login_div">
            <form action="{% url 'account:login' %}" method="post" style="width: 200px;">
                <input type="hidden" id="form_key" name="form_key" value="Mr1VlmxjqlexWFJBlE5f">
            <div >
                <input class="account_input" name="email" required="true" type="text" placeholder="邮箱">                
            </div>
                <div>
                <input class="account_input" name="password" required="true" type="password"  placeholder="密码">
			    </div>	
                <!--
				<input type="checkbox"/>下次自动登录&nbsp;|&nbsp;<a href="/account/forget">密码忘记了?</a>
                -->
			   <div  class="login_button">
                    <input id="submit" type="submit"  class="btn_submit" value="登&nbsp;录">
                </div>

			</form>  
		</div>
		</div>
    </div>
{% endblock %}

{% block aside %}
<div class="title">或者使用第三方登录平台</div>
<div class="login_form">
<a class="login_weibo" href="{% url 'account:weibo_login' %}"><span class="zg-ico-sina"></span>新浪微博登录</a>
</div>
<div class="pl">
<p>&gt;&nbsp;还没有公舍帐号? <a href="{% url 'account:signup' %}">注册</a></p>
</div>
{% endblock %}

gongshare/templates/people.html
{% extends "base.html" %}
{% block title %} gongshare---共同协作 {% endblock %}
{% load custom_filter %}
{% block content %}  
<div class="horizontal_tabs feed_switcher">
    <ul class="list_contents" >
        <li class="tab linked_list_item first">
        <a class="link {%if not favoured %}selected {%endif%}" href="/people/{{user.id}}/">
            {%ifequal user user_ %}我{% else %}{{user.username}}{% endifequal %}发布的主题
        </a></li>
        <li class="tab linked_list_item">
        <a class="link {%if favoured %}selected {%endif %}" href="/people/{{user.id}}/favour">
         {%ifequal user user_ %}我{% else %}{{user.username}}{% endifequal %}赞过的主题   
        </a></li>
    </ul>
</div>

<div class="content">
	{% if subject_list %}
	<div id="subject-wrapper" >
	{% for subject in subject_list %}
	<div class="subject-item " data-id="{{subject.id}}">
		{% if subject.user != user_ or favoured%}
		<div class="subject-votebar">
			{% if subject in user_.vote_subjects.all %}
				<button class="up pressed"  original-title="取消赞"><span class="vote-arrow"></span>取消赞</button>
			{%else%}
				<button class="up"  original-title="赞一个"><span class="vote-arrow"></span>赞同</button>
			{%endif %}
		</div>
		{% endif %}
		<div class="answer-head">
		<div class="zm-item-answer-author-info">
			<h3 class="zm-item-answer-author-wrap"><a href="{{subject.url}}" target="_blank">
            <strong  class="zu-question-my-bio">{{subject.title}}</strong></a>
            <span class='zm-item-domain'>({{subject.netloc}})</span></h3>
		</div>
		</div>
		<div class="subject-item-meta zm-item-comment-el answer-actions clearfix">
		    <span>{{subject.votes}}票</span>
        	{% if favoured %}<a  href="/people/{{subject.user}}" class="meta-item" >{{subject.user.username}}</a>{%endif %}
            <a href="/subject/{{subject.id}}" name="addcomment" class=" meta-item toggle-comment">
            <i class="z-icon-comment"></i>
            {% if subject.comment_count %} {{subject.comment_count}}条评论{% else %}添加评论{%endif %}</a>
			<a href="javascript:;" class="meta-item zu-autohide" name="share"><i class="z-icon-share"></i>分享</a>
			<a href="javascript:;" class="meta-item zu-autohide fav" name="report"><i class="z-icon-collect"></i>举报</a>
            {% if not favoured %}
            <span class="answer-date-link-wrap meta-item" title='{{subject.pub_date|date:"Y-m-d H:i"}}'>
            {{subject.pub_date|timebefore}}
            </span>
            {% endif %}
		</div>
	</div>
	{% endfor %}
	</div>
	{% endif %}
</div>
<div class="paginator">
    {% if subject_list.has_next%}
    <a href="?p={{subject_list.next_page_number}}">更多</a>
    {% endif %}
</div>
{% endblock %}

{% block aside %}
    <div class='profile'>
        <img src="/media/avatar/{{avatar}}" height="80px" width="80px" class="userface">
        <div class="userinfo clearfix">
            <ul>
                <li>{{user.username}}</li>
                <li>{{user.add_time|date:"Y-m-d"}} 加入</li>
                <!--<li><a href="http://liuzhijun.iteye.com">liuzhijun.iteye.com</a></li>
                <li><span style="font-weight:bold">123</span>点声望</li>-->
            </ul>
        </div>
        <div class="userintro">
            <div class="show-intro">
                <span>{{user.signature}}</span>
                {% if user == user_ %}
                <a class="edit-button" name="edit" href="javascript:;">
                {%if user.signature %}修改{%else %}一句话介绍自己{%endif%}</a>
                {% endif %}
            </div>
            {% if user == user_ %}
        <div class="intro_wrapper" style="display: none;">
            <textarea id="intro_content" name="intro" style="overflow: hidden;">{{user.signature}}</textarea><br>
            <input id="intro_url" type='hidden' value="/people/{{user.id}}/edit_intro/">
            <input id="intro_submit" class="submit" type="submit" value="保存">
            <a id="intro_cancel" class="cancel" href="javascript:;"> 取消</a>
        </div>
            {% endif %}
            
        </div>
    </div>
{% endblock %}

gongshare/templates/signup_active.html
{% extends "base.html" %}
{% block title %}激活账户{% endblock %}
{% block content %}
<div id="content">
    <div class="title">账户激活</div>
    <div class="register">
    <div class="point_email">
        <p>系统已经发送了一封激活邮件到您的邮箱</p>
        <p>请访问您的邮箱：<b>{{email}}</b>，点击邮件中的链接便可激活您的帐户</p>
    </div>
    <div class="other">
        <p>&nbsp;&nbsp;如果没有收到激活邮件：</p>
        <p>• 也许邮件被您的邮箱误认为是垃圾邮件而放到垃圾箱中，请检查一下</p>
        <!--<p>• 或者，您可以<a id="sendMsg" class="action" href="javascript:void(0)">点此重新发送激活邮件</a></p>
        -->
    </div>
    </div>

</div>
{% endblock %}



gongshare/templates/subject_detail.html
{% extends "base.html" %}
{% block title %} {{subject.title}}{% endblock %}
{% block content %}  

<div class="content">
	<div  class="subject-detail">
	<div class="subject-item" data-id="{{subject.id}}">
		<div class="subject-votebar">
			{% if subject in user_.vote_subjects.all %}
			<button class="up pressed"  original-title="取消赞"><span class="vote-arrow"></span>取消赞</button>
			{%else%}
			<button class="up"  original-title="赞一个"><span class="vote-arrow"></span>赞同</button>
			{%endif %}
		</div>
		<div class="answer-head">
			<div class="zm-item-answer-author-info">
			<h3 class="zm-item-answer-author-wrap"><a href="{{subject.url}}" target="_blank">
			<strong  class="zu-question-my-bio">{{subject.title}}</strong></a><span class='zm-item-domain'>({{subject.netloc}})</span></h3></div>
		</div>
		<div class="subject-tag">
		{% for tag in subject.tags.all %}<span class="post-tag">{{tag}}</span>{% endfor %}
		</div>
		<div class="subject-detail">{{subject.content|safe}}</div>
		<div class="subject-item-meta clearfix">
			<span>{{subject.votes}} 票</span>
			<span class="answer-date-link-wrap meta-item">{{subject.pub_date|date:"Y-m-d"}}</span>
            <a  href="{% url 'people:index' subject.user.id %}" class="meta-item" >{{subject.user.username}}</a>
			<a href="javascript:;" class="meta-item" name="share">分享</a>
            {% ifequal user_ subject.user %}
            <a href="{% url 'subject:edit' subject.id}" name="edit" class="meta-item zu-autohide edit">修改</a>
			<a href="javascript:;" class="meta-item zu-autohide del" name="delete">删除</a>
            {% else %}
			<a href="javascript:;" class="meta-item  fav" name="report">举报</a>
            {% endifequal %}
		</div>
    </div>
		<div class="zm-item-meta zm-item-comment-el clearfix" id="zh-question-meta-wrap">
		<div class="panel-container panel-border">
			<div class="zm-comment-box" data-count={{subject.comment_count}}>
			<div class="zm-comment-list">
			{% for comment in comments %}
				 <div class="zm-item-comment" data-id="{{comment.id}}">
					 <div class="zm-comment-content-wrap">
					 <div class="zm-comment-hd">
                         <a href="{% url 'people:index' comment.user.id %}" class="zg-link">{{comment.user.username}}</a>
						 {% if comment.comment %}
						 <span class="desc">回复 </span>
                         <a  href="{% url 'people:index' comment.comment.uesr.id %}" class="zg-link" >{{comment.comment.user.username}}</a>
						 {% endif %}
					 </div>
					  
                     <div class="zm-comment-content">
                         {% if comment.comment %}
                         <blockquote>
                             <p>{{comment.comment.content}}</p>
                         </blockquote>
                         {% endif %}
                         <p>{{comment.content}}</p>
                     </div>
					 <div class="zm-comment-ft">
                        {% ifnotequal user_ comment.user %}
						<a href="javascript:;" class="reply zm-comment-op-link" name="reply_comment">回复</a>
						<a href="javascript:;" class="like zm-comment-op-link " name="like_comment">
						{% if user_ not in comment.like_users.all %}赞{% else%} 已赞{%endif%}</a>
						<a href="javascript:;" name="report" class="report zm-comment-op-link">举报</a>
                        {% endifnotequal %}
						<span class="like-num"><em>{{comment.like}}</em> <span>赞</span></span>
                        {% ifequal user_ comment.user %}
						<a href="javascript:;" name="delete" class="delete zm-comment-op-link">删除</a>
                        {% endifequal %}
						<span class="date">{{comment.pub_date|date:"Y-m-d"}}</span>
					 </div>
					 </div>
				 </div>
			{% endfor %}
			</div>
			<div class="zm-comment-form zm-comment-box-ft">
				<div class="zm-comment-editable editable" aria-label="写下你的评论" contenteditable="true">
					<p style="color:#999">写下你的评论</p>
				</div>
				<div class="zm-command zg-clear">
					<a href="javascript:;" name="addnew" id="add_comment" class="zg-right zg-btn-blue">评论</a>
					<a href="javascript:;" name="closeform" class="zm-command-cancel">取消</a>
				</div>
				<div class="zm-comment-info"></div>
			</div>
			</div>
		</div>
		</div>
	</div>
</div>
{% endblock %}

gongshare/templates/subject_list.html
{% extends "base.html" %}
{% block title %}gongshare Python编程 发现 分享 传播 技术{% endblock %}
{% block content %}  
{% load custom_filter %}

{% if home %}
<div class="horizontal_tabs feed_switcher">
    <ul class="list_contents">
        <li class="tab linked_list_item first"><a class="link {%if not recent %}selected {%endif%}" href="{% url 'subject:hot' %}">热门资源</a></li>
    <li class="tab linked_list_item"><a class="link {%if recent %}selected {%endif %}" href="{% url 'subject:recent' %}">最近资源</a></li>
	</ul>
<div class="e_col side_col above_feed_add_q_button">
	<a class="button button-primary button-share icon-button" href="#" style="margin-top: -13px;">
	<span class="has_icon_link icon_add_question" >发布资源</span></a></div>
</div>
{% endif %}

<div class="content">
    {%if query_key %}
    <div class='search-result-head'><h2>“{{query_key}}”的搜索结果{% if count > 0 %}共{{count}}条{%endif %}：</h2></div>
    {%endif %}
	{% if subject_list %}
	<div id="subject-wrapper" >
	{% for subject in subject_list %}
		<div class="subject-item " data-id="{{subject.id}}">
        {% ifnotequal subject.user user_ %}
			<div class="subject-votebar">
            {% if subject in user_.vote_subjects.all %}
            <button class="up pressed"  original-title="取消赞"><span class="vote-arrow"></span>取消赞</button>
            {%else%}
            <button class="up"  original-title="赞一个"><span class="vote-arrow"></span>赞同</button>
            {%endif %}
			</div>
        {% endifnotequal %}
		    <div class="answer-head">
				<div class="zm-item-answer-author-info"><h3 class="zm-item-answer-author-wrap">
                <a href="{{subject.url}}" target="_blank">
                <strong  class="zu-question-my-bio">{{subject.title}}</strong></a>
                <span class='zm-item-domain'>({{subject.netloc}})</span></h3>
				</div>
			</div>
			<div class="subject-item-meta zm-item-comment-el answer-actions clearfix">
				<span>{{subject.votes}}票</span>
                <a  href="{% url 'people:index' subject.user.id %}" class="meta-item" >{{subject.user.username}}</a> 
                <a href=" {% url 'subject:detail' subject.id %}" name="addcomment" class=" meta-item toggle-comment">
				{% if subject.comment_count %} {{subject.comment_count}}条评论{% else %}评论{%endif %}</a>
				<a href="javascript:;" class="meta-item zu-autohide" name="share">分享</a>
                {% ifequal user_ subject.user %}
                <a href="{% url 'subject:edit' subject.id %}" class="meta-item zu-autohide edit" name="edit">修改</a>
				<a href="javascript:;" class="meta-item zu-autohide del" name="delete">删除</a>
                {% else %}
                <a href="javascript:;" class="meta-item zu-autohide fav" name="report">举报</a>
                {% endifequal %}
				<span class="answer-date-link-wrap meta-item" title='{{subject.pub_date|date:"Y-m-d H:i"}}'>
				{{subject.pub_date|timebefore}}</span>
				<span class="copyright zu-autohide"></span>
			</div>
		</div>
	  {% endfor %}
	</div>
	{% else %}
    <span style="font-size:14px">OHOH，找不到东东</span>
    {% endif %}

</div>
<div class="paginator">
    {% if subject_list.has_next%}
    <a href="?p={{subject_list.next_page_number}}">更多</a>
    {% endif %}
</div>

{% endblock %}